# Generated by Django 5.2 on 2025-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('duracao_minutos', models.IntegerField()),
            ],
        ),
    ]
